configuration.
NCI-Agency/ansible.anet.playbook pull request #9
Opened 2020-10-21 14:46 UTC by midmarch

- Configure Keycloak clients, in line with [Setting up Keycloak (user authentication)](https://github.com/NCI-Agency/anet/blob/keycloak-integration/docs/keycloak.md):
  - Creates the server client: "ANET-Client"
  - Creates the public client: "ANET-Client-public"
- Introduces a dependency on [keycloak_client](https://docs.ansible.com/ansible/latest/collections/community/general/keycloak_client_module.html) which is a plugin part of the [community.general collection](https://docs.ansible.com/ansible/latest/collections/community/general/).
- Move the internal Keycloak HTTP ports configuration to the Ansible Keycloak role

2020-10-26 09:02 UTC, gjvoosten requested changes

2020-10-26 09:02 UTC, gjvoosten commented on roles/keycloak/tasks/client-config.yml
> +    service_accounts_enabled: yes
Should be `no` for a public client.

2020-10-26 09:02 UTC, gjvoosten commented on roles/keycloak/tasks/client-config.yml
> +    public_client: no # Access Type = confidential
Add missing line:
```
    service_accounts_enabled: yes
```

2020-10-26 09:02 UTC, gjvoosten commented on roles/keycloak/tasks/start.yml
> +    msg: 'KeyCloak HTTP port {{ keycloak_http_port }} is not listening'
`KeyCloak` ⇒ `Keycloak`

2020-11-11 13:43 UTC, midmarch commented on roles/keycloak/tasks/client-config.yml
> +- name: 'Keycloak client: ANET confidential client (used by the server-side)'
It is required for the semicolon.

2020-11-11 13:49 UTC, midmarch commented on roles/keycloak/tasks/start.yml
> +    msg: 'KeyCloak HTTP port {{ keycloak_http_port }} is not listening'
:heavy_check_mark:

2020-11-11 13:49 UTC, midmarch commented on roles/keycloak/tasks/client-config.yml
> +    public_client: no # Access Type = confidential
:heavy_check_mark:

2020-11-11 13:49 UTC, midmarch commented on roles/keycloak/tasks/client-config.yml
> +    service_accounts_enabled: yes
:heavy_check_mark:

2020-11-25 14:25 UTC, merged